### PR TITLE
docs: update landing page Vue example to script setup

### PR DESCRIPTION
**Pull request by wobsoriano**
This PR updates Vue snippets from JSX to [<script setup>](https://vuejs.org/api/sfc-script-setup.html#script-setup). It is the recommended syntax for SFC + Composition API.

### CODE REVIEW

**Comment by wobsoriano** [comment]
Do we still need to keep the `JSX` examples or just overwrite it with SFC script setup?

**Comment by segunadebayo** [comment]
Thanks for working on this @wobsoriano. We prefer to "add" the Vue SFC as another tab so users can use whatever syntax they want.

The tabs will be "React", "Solid", "Vue SFC", "Vue JSX". You get what I mean?

**Comment by wobsoriano** [comment]
> Thanks for working on this @wobsoriano. We prefer to "add" the Vue SFC as another tab so users can use whatever syntax they want.
> 
> The tabs will be "React", "Solid", "Vue SFC", "Vue JSX". You get what I mean?

Got it!

**Comment by anubra266** [comment]
Thanks for this @wobsoriano. Will close this now as the examples will get added in #25

**Pull request closed without merging**
