### PR TITLE
chore: add theme toggle

### PR DESCRIPTION
**Pull request by anubra266**
Add dark mode

### CODE REVIEW

**Comment by jer3m01** [comment]
Hi, would you mind if I continued this PR?

**Comment by anubra266** [comment]
@jer3m01 The dark mode styles for the site isn't implemented yet.

**Comment by jer3m01** [comment]
> @jer3m01 The dark mode styles for the site isn't implemented yet.

I would like to implement them.

**Comment by anubra266** [comment]
@jer3m01 Feel free then.

**Comment by anubra266** [comment]
@jer3m01 The codeblocks would be the main stuff. We'll need to change the current approach, to accommodate for different matching syntax highlighting in light and dark modes respectively

**Pull request closed without merging**
